#Database
spring:
  data:
    mongodb:
      database: post-liker
      host: localhost
      port: 27017
      authentication-database: admin
      username: rootuser
      password: rootpass

#JWT
jwt:
  secret: 66546A576E5A7234753778214125442A472D4B6150645267556B587032733576
  expire-minutes: 30